#!/bin/bash
jlpm

# initially list installed extensions to determine if there are any surprises
jupyter labextension list

# install the labextension
jupyter labextension install --no-build .

# verify the list of extensions
jupyter labextension list

# verify the list of extensions
jupyter lab build --debug --dev-build=False --minimize=True

# verify the list of extensions one last time
jupyter labextension list
